all_joints:
- - 0
- - 1
- - 2
- - 3
- - 4
- - 5
- - 6
- - 7
- - 8
all_joints_names:
- body_center
- body_left
- body_right
- eye_left
- eye_right
- neck_center
- snout
- tail_stem
- tail_tip
batch_size: 1
bottomheight: 400
crop: true
cropratio: 0.4
dataset: training-datasets/iteration-0/UnaugmentedDataSet_of-rodent-tracking-959-18-single-passMay3/of-rodent-tracking-959-18-single-pass_LK95shuffle1.mat
dataset_type: default
display_iters: 1000
global_scale: 0.8
init_weights: /home/pop/Programs/Miniconda3/envs/deepcut2/lib/python3.6/site-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_101.ckpt
intermediate_supervision: false
intermediate_supervision_layer: 12
leftwidth: 400
location_refinement: true
locref_huber_loss: true
locref_loss_weight: 0.05
locref_stdev: 7.2801
max_input_size: 1500
metadataset: training-datasets/iteration-0/UnaugmentedDataSet_of-rodent-tracking-959-18-single-passMay3/Documentation_data-of-rodent-tracking-959-18-single-pass_95shuffle1.pickle
min_input_size: 64
minsize: 100
mirror: false
multi_step:
- - 0.01
  - 10000
- - 0.005
  - 130000
- - 0.002
  - 230000
- - 0.001
  - 930000
net_type: resnet_101
num_joints: 9
pos_dist_thresh: 17
project_path: /home/pop/GitHub/Gradu-2-0-deeplabconfig/959-18-training
rightwidth: 400
save_iters: 10000
scale_jitter_lo: 0.5
scale_jitter_up: 1.25
topheight: 400
